### ISSUE TITLE
Xcode project needs modifying after every Unity export

### ISSUE THREAD

**Issue by jamesncl** [learntoflutter/flutter_embed_unity#1]
Currently, every time you export Unity using `Flutter embed -> Export project to Flutter app (ios)` you then need to remember to change the target membership of the Data folder to UnityFramework, and add the linker flags `-Wl,-U,_FlutterEmbedUnityIos_sendToFlutter` to the Unity-iPhone project build settings.

It would be better if this was automated as part of [the export](https://github.com/jamesncl/flutter_embed_unity/blob/main/example_unity_2022_3_project/Assets/FlutterEmbed/Editor/ProjectExporterIos.cs), using [Unity's PBXProject editing tool](https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.html). Looking for anyone with experience with editing Xcode project files to help on this :)

**Comment by AkhilRaja** [comment]
I can work on this and PR. Is there a discord channel or a place where we could communicate ?

**Comment by learntoflutter** [comment]
That would be really kind of you. I've just set up [Github discussions](https://github.com/learntoflutter/flutter_embed_unity/discussions)
