### ISSUE TITLE
[Android] Flutter 3.16 and 3.19 make the widget invisible on Android < 10

### ISSUE THREAD

**Issue by timbotimbo** [learntoflutter/flutter_embed_unity#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.13.9 and 3.16.5

### Description

I copied this over from flutter_unity_widget, as I was able to reproduce this with your plugin too.

When using this widget with the default settings on Flutter 3.16, the widget is invisible on Android < 10.
Run the example with both Flutter 3.13.9 and 3.16.5.
On Android versions < 10 the widget will be invisible with Flutter 3.16.5

This seems to be a bug with Flutter, and not this plugin. But it is good to know the issue exists.
I've created [this issue](https://github.com/flutter/flutter/issues/141068) in the Flutter repo, see that for more details.

**Videos**

There is a red container behind Unity, to show when it is transparent/invisible.
(Samsung Galaxy S8, Android 9)
<table>
<tr><th>3.13.9  Visible</th><th> 3.16.5 Invisible</th></tr>
<tr>
<td>

https://github.com/flutter/flutter/assets/11444698/e5e41192-7da7-4e04-9715-52804883ca33
</td>
<td>

https://github.com/flutter/flutter/assets/11444698/c68547ac-217b-4381-b0ba-bcf7c8b19b9c
</td>
</tr>
</table>

### Minimum reproducible example (MRE)

You can use your existing example project without any changes.

Alternatively [this repo](https://github.com/timbotimbo/flutter_fuw_reproduction_android/tree/flutter_embed_unity) includes an android export and can be run with Flutter only. I hacked an export from Unity 2019.4.40 into this one as that version prebuildd the unityLibrary, which makes it much more portable.

### What platforms are you seeing the problem on?

Android

### Devices

 - Android 9 emulator (ChromeOS export in Unity)
 - Samsung Galaxy S8, Android 9
 - Samsung Galaxy J5, Android 6.
 - WileyFox Swift, Android 7.2.1

### Anything else?

Incidentally, I discovered that I can use the `android/unityLibrary` folder exported using the flutter_unity_widget unitypackage with this plugin too.
Naturally messaging to Flutter and plugin specific stuff like that won't work, but it is good to know for reproducing platform view bugs.

**Comment by jamesncl** [comment]
Thank you so much for the detailed report! This is excellent work. I was about to update to 3.16, so you have saved my day. Looks like the issue you raised in the Flutter repo is being worked on and will hopefully the fix will be merged soon. In the meantime I will update the readme for this package with a note.

**Comment by timbotimbo** [comment]
I did some testing to see in which version this is fixed.
Even though the fix was included on master on jan 9 2024, the following beta releases still have the bug.

I tested some tags on the flutter repo:
broken: 
- tag 3.19.0-0.2.pre 
- tag 3.19.0-0.3.pre (jan 26)
- tag 3.19.0-0.4.pre (feb 2)

works:
- commit 883418674118cdd611d8cc2de303826409705267  jan 9
- tag 3.20.0-0.0.pre (feb 2)

**Comment by timbotimbo** [comment]
Fixed in the new 3.19 stable release.

**Comment by timbotimbo** [comment]
Not fixed on the new 3.19 stable.
it is fixed on public beta 3.20.0-1.1.pre

**Comment by jamesncl** [comment]
Thanks for the update. Disappointing that the fix wasn't included in 3.19.0 :(

**Comment by timbotimbo** [comment]
The fix was included in the new 3.22.0 release.
