### ISSUE TITLE
Agora framework not linked properly

### ISSUE THREAD

**Issue by mriaz764** [learntoflutter/flutter_embed_unity#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.22.1

### Description

dyld[3183]: Library not loaded: @rpath/AgoraContentInspectExtension.framework/AgoraContentInspectExtension
  Referenced from: <6AA5D092-81D2-36FE-B799-7660DDDB3A68> /private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/usr/lib/swift/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/usr/lib/swift/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file), '/private/var/containers/Bundle/Application/CD40B97D-46DF-4EF1-A7BA-20A8E4844C77/Runner.app/Frameworks/AgoraContentInspectExtension.framework/AgoraContentInspectExtension' (no such file)
  
<img width="1403" alt="Screenshot 2024-08-06 at 9 36 21 PM" src="https://github.com/user-attachments/assets/5ea8348f-3665-4254-8792-3f782af740b6">

<img width="1395" alt="Screenshot 2024-08-06 at 9 41 53 PM" src="https://github.com/user-attachments/assets/cac4e74d-6f5c-4312-9256-3eb00a07c3e9">

### What platforms are you seeing the problem on?

iOS

**Comment by mriaz764** [comment]
<img width="1400" alt="Screenshot 2024-08-06 at 9 45 02 PM" src="https://github.com/user-attachments/assets/0b95e2aa-3f3d-4ce9-a4ed-de274c38e86e">
<img width="1458" alt="Screenshot 2024-08-06 at 9 45 36 PM" src="https://github.com/user-attachments/assets/46bb1c8b-ebc9-4ffa-98b0-0195c0e6d5e0">

**Comment by jamesncl** [comment]
This looks similar to the [Framework not found FBLPromises issue](https://pub.dev/packages/flutter_embed_unity#framework-not-found-fblpromises). Perhaps the solution detailed there will help?

**Comment by mriaz764** [comment]
I resolved this issue after adding agora's frameworks also into flutter main ios project
<img width="1398" alt="Screenshot 2024-08-07 at 4 41 02 PM" src="https://github.com/user-attachments/assets/effc0f19-5c12-47db-98ce-ceb4f2a5ee3d">
